services:
  traefik:
    container_name: ${TRAEFIK_CONTAINER_NAME:-traefik}
    restart: always
    image: traefik
    hostname: traefik
    env_file:
      - ./traefik.env
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
    volumes:
      - traefik-config:/etc/traefik
      - traefik-certs:/etc/traefik/certs
      - traefik-plugins:/etc/traefik/plugins-local
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Admin Interface
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DEFAULT_TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    networks:
      traefik:
  
  casdoor:
    image: casbin/casdoor
    container_name: ${CASDOOR_CONTAINER_NAME:-casdoor}
    restart: unless-stopped
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.casdoor.entrypoints=websecure"
      - "traefik.http.services.casdoor.loadbalancer.server.port=8000"
      - "traefik.http.routers.casdoor.tls=true"
      - "traefik.docker.network=traefik"
    volumes:
      - casdoor-conf:/conf/
    networks:
      traefik:
      casdoor:
    ports:
      - "18000:8000"
  
  casdoor-statics:
    container_name: ${CASDOOR_STATICS_CONTAINER_NAME:-casdoor-statics}
    image: halverneus/static-file-server
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.casdoorstatics.entrypoints=websecure'
      - 'traefik.http.routers.casdoorstatics.tls=true'
    volumes:
      - casdoor-statics:/web
    networks:
      traefik:
  mariadb:
    container_name: ${CASDOOR_MARIADB_CONTAINER_NAME:-casdoor-mariadb}
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: casdoor
      MYSQL_USER: casdoor
      MYSQL_PASSWORD: "${CASDOOR_MYSQL_PASSWORD}"
    volumes:
      - casdoor-mariadb:/var/lib/mysql
      - casdoor-mariadb_config:/etc/mysql/conf.d
    networks:
      casdoor:


  komodo-mongo:
    image: mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
  
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: ${KOMODO_CONTAINER_NAME:-komodo}
    restart: unless-stopped
    depends_on:
      - mongo
    labels:
      - komodo.skip: # Prevent Komodo from stopping with StopAllContainers
      - "traefik.enable=true"
      - "traefik.http.routers.komodo.entrypoints=websecure"
      - "traefik.http.services.komodo.loadbalancer.server.port=8000"
      - "traefik.http.routers.komodo.tls=true"
      - "traefik.docker.network=traefik"
    env_file: ./casdoor.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      ## Core cache for repos for latest commit hash / contents
      - repo-cache:/repo-cache
    networks:
      traefik:
      komodo:

  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    env_file: ./compose.env
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    networks:
      traefik:

volumes:
  traefik-config:
  traefik-certs:
  traefik-plugins:
  casdoor-conf:
  casdoor-statics:
  casdoor-mariadb:
  casdoor-mariadb_config:
  casdoor-auth:
  komodo-mongo-data:
  komodo-mongo-config:
  komodo-repo-cache:

networks:
  traefik:
    ipam:
      config:
        - subnet: ${TRAEFIK_SUBNET}
  casdoor:
  komodo:
